# Generated by Django 4.2.1 on 2023-06-15 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250, verbose_name='content')),
                ('priority', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], db_index=True, default=0, null=True, verbose_name='priority')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Not started'), (1, 'In progess'), (2, 'Completed'), (3, 'On hold'), (4, 'Cancelled')], db_index=True, default=0, null=True, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee_tasks', to=settings.AUTH_USER_MODEL, verbose_name='assignee')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_tasks', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250, verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task_manager.task', verbose_name='task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'task comment',
                'verbose_name_plural': 'task comments',
            },
        ),
    ]
