# Generated by Django 4.2.2 on 2023-06-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='read_at',
            field=models.DateTimeField(null=True),
        ),
    ]
