# Generated by Django 4.2.2 on 2023-06-21 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_manager', '0005_task_is_read_task_read_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcomment',
            name='user',
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='commenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='commenter'),
        ),
    ]
