# Generated by Django 4.2.2 on 2023-06-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_remove_taskcomment_user_taskcomment_commenter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'task comment', 'verbose_name_plural': 'task comments'},
        ),
    ]
