# Generated by Django 4.2.2 on 2023-06-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_alter_taskcomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not started'), (1, 'In progess'), (2, 'On hold'), (3, 'Cancelled'), (4, 'Completed')], db_index=True, default=0, verbose_name='status'),
        ),
    ]
