# Generated by Django 4.2.2 on 2023-06-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', 'finish', '-priority'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
    ]
