# Generated by Django 4.2.2 on 2023-06-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0009_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='note'),
        ),
    ]
